import type { ITheme } from '@xterm/xterm';
// GitHub Light Default: https://github.com/mbadolato/iTerm2-Color-Schemes
// MIT license: public/licenses/iterm2-color-schemes.txt.
// Catppuccin Ghostty palette: https://github.com/catppuccin/ghostty
// MIT license distributed in public/licenses/catppuccin.txt.
export const terminalThemes = {
  githubLight: {
    black: '#24292f',
    red: '#cf222e',
    green: '#116329',
    yellow: '#4d2d00',
    blue: '#0969da',
    magenta: '#8250df',
    cyan: '#1b7c83',
    white: '#6e7781',
    brightBlack: '#57606a',
    brightRed: '#a40e26',
    brightGreen: '#1a7f37',
    brightYellow: '#633c01',
    brightBlue: '#218bff',
    brightMagenta: '#a475f9',
    brightCyan: '#3192aa',
    brightWhite: '#8c959f',
    background: '#ffffff',
    foreground: '#1f2328',
    cursor: '#0969da',
    cursorAccent: '#3c9cff',
    selectionBackground: '#1f2328',
    selectionForeground: '#ffffff',
  },
  mocha: {
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#a6adc8',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#bac2de',
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#11111b',
    selectionBackground: '#353749',
    selectionForeground: '#cdd6f4',
  },
} satisfies Record<'githubLight' | 'mocha', ITheme>;
