packages:
  - .
  - distribution/site
  - merch-store
allowBuilds:
  electron-winstaller: false
  electron: true
  better-sqlite3: true
  esbuild: true
  node-pty: true
patchedDependencies:
  '@pierre/diffs@1.5.1': patches/@pierre__diffs@1.5.1.patch
