import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test';
import { mkdtemp, chmod, readFile, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { Store } from '../../electron/db/store';
import { randomUUID } from 'node:crypto';

let app: ElectronApplication;
let dir: string;
test.afterEach(async () => { if (app) await app.close().catch(() => {}); if (dir) await rm(dir, { recursive: true, force: true }); });
async function launch(seed?: (store: Store) => void) {
  dir = await mkdtemp(join(tmpdir(), 'moose-e2e-'));
  const fixture = resolve('tests/fixtures/agent.mjs'); await chmod(fixture, 0o755);
  const store = new Store(join(dir, 'moose.sqlite'));
  store.setSettings({ language: 'en', theme: 'light', codexPath: fixture, grokPath: fixture }); seed?.(store); store.close();
  const env: Record<string, string> = Object.fromEntries(Object.entries({ ...process.env, MOOSE_DATA_DIR: dir }).filter((entry): entry is [string, string] => typeof entry[1] === 'string')); delete env.ELECTRON_RUN_AS_NODE;
  app = await electron.launch({ args: ['.'], env });
  const page = await app.firstWindow(); await page.waitForSelector('.app-shell');
  return page;
}
test('opens a project, approves a real IPC turn, reviews diff, persists draft and switches themes', async () => {
  const page = await launch(); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const projectDir = join(dir, 'project'); execFileSync('/usr/bin/git', ['init', '-q', projectDir]);
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, projectDir);
  await page.locator('.welcome').getByRole('button', { name: 'Open project' }).click();
  await expect(page.locator('.project-heading')).toContainText('project');
  await page.locator('#composer').fill('Implement a focused change'); await page.locator('#composer').press('Enter');
  await page.getByRole('button', { name: 'Allow once', exact: true }).click();
  await expect(page.locator('.markdown')).toContainText('Implemented the change.');
  expect(await readFile(join(projectDir, 'approved.txt'), 'utf8')).toBe('moose-approved\n');
  await page.getByRole('button', { name: 'Review changes', exact: true }).click(); await page.locator('.change-file').click();
  await expect(page.locator('.diff-code')).toContainText('+moose-approved');
  await page.locator('#composer').fill('Saved draft'); await expect.poll(async () => (await page.evaluate(() => window.moose.request('snapshot', {}))).sessions[0].draft).toBe('Saved draft');
  const capability = await page.evaluate(() => ({ node: typeof (window as unknown as { require?: unknown }).require, keys: Object.keys(window.moose) })); expect(capability.node).toBe('undefined'); expect(capability.keys.sort()).toEqual(['request', 'subscribe']);
  await expect(page.evaluate(() => window.moose.request('openExternal', { url: 'file:///etc/passwd' }))).rejects.toThrow();
  await page.screenshot({ path: 'test-results/workspace-light.png' });
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('combobox', { name: 'Theme', exact: true }).click(); await page.getByRole('option', { name: 'Dark', exact: true }).click();
  await expect(page.locator('html')).toHaveClass('dark');
  await page.getByRole('combobox', { name: 'Language', exact: true }).click(); await page.getByRole('option', { name: '简体中文' }).click();
  await expect(page.getByRole('heading', { name: '通用', exact: true })).toBeVisible();
  await expect(page.getByRole('option', { name: '简体中文' })).toHaveCount(0);
  await page.screenshot({ path: 'test-results/settings-dark.png' });
  await page.keyboard.press('Escape');
  await page.screenshot({ path: 'test-results/workspace-dark.png' });
  expect(errors).toEqual([]);
});
test('handles 10,000 persisted events, paging, IME input, archive and restore', async () => {
  let sessionId = '';
  const page = await launch(store => {
    const project = store.addProject(dir), session = store.createSession(project.id, 'codex'); sessionId = session.id;
    store.updateSession(session.id, { title: 'Long conversation', status: 'completed' });
    const runId = randomUUID();
    store.sqlite.transaction(() => { for (let i = 0; i < 10000; i++) store.saveMessage({ id: randomUUID(), runId, sessionId, seq: i + 1, kind: 'assistant', title: '', state: 'done', text: `Historical entry ${i}`, createdAt: i }); })();
  });
  await page.locator('.session-row').filter({ hasText: 'Long conversation' }).click();
  await expect(page.locator('.markdown')).toHaveCount(80);
  const start = Date.now(); await page.locator('#composer').fill('正在输入'); expect(Date.now() - start).toBeLessThan(1000);
  await page.locator('#composer').dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true });
  expect(await page.locator('#composer').inputValue()).toBe('正在输入');
  expect((await page.evaluate(id => window.moose.request('queue', { sessionId: id }), sessionId)).length).toBe(0);
  await page.getByRole('button', { name: 'Load earlier messages' }).click(); await expect(page.locator('.markdown')).toHaveCount(160);
  await page.getByRole('button', { name: 'Rename', exact: true }).click(); await page.getByLabel('Session title').fill('Renamed conversation'); await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.locator('.header-title')).toHaveText('Renamed conversation');
  await page.getByRole('button', { name: 'Archive', exact: true }).click(); await page.getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.locator('#composer')).toBeDisabled();
  await page.getByRole('button', { name: 'Restore', exact: true }).click(); await expect(page.locator('#composer')).toBeEnabled();
  await app.close();
  const env = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[0] !== 'ELECTRON_RUN_AS_NODE'));
  app = await electron.launch({ args: ['.'], env: { ...env, MOOSE_DATA_DIR: dir } });
  const restored = await app.firstWindow(); await expect(restored.locator('#composer')).toHaveValue('正在输入'); await expect(restored.locator('.header-title')).toHaveText('Renamed conversation');
});
test('Grok approval denial and questions travel through ACP, and cancellation preserves queue', async () => {
  const page = await launch(); const projectDir = join(dir, 'grok-project'); execFileSync('/usr/bin/git', ['init', '-q', projectDir]);
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, projectDir);
  await page.locator('.welcome').getByRole('button', { name: 'Open project' }).click();
  await page.getByRole('combobox', { name: 'Agent', exact: true }).click(); await page.getByRole('option', { name: 'Grok Build', exact: true }).click();
  await page.locator('#composer').fill('Change this'); await page.locator('#composer').press('Enter');
  await page.getByRole('button', { name: 'Deny', exact: true }).click(); await expect(page.locator('.markdown')).toContainText('Permission denied.');
  await page.locator('#composer').fill('ask'); await page.locator('#composer').press('Enter');
  await expect(page.getByText('Which approach?', { exact: true })).toBeVisible();
  await page.getByPlaceholder('Your answer', { exact: true }).fill('Small change'); await page.getByRole('button', { name: 'Send answer' }).click(); await expect(page.locator('.markdown').last()).toContainText('Answer received.');
  await page.locator('#composer').fill('hold'); await page.locator('#composer').press('Enter'); await expect(page.getByRole('button', { name: 'Stop task' })).toBeVisible();
  await page.locator('#composer').fill('queued followup'); await page.locator('#composer').press('Enter');
  await page.getByRole('button', { name: 'Stop task' }).click(); await page.locator('.queue-panel summary').click();
  await expect(page.locator('.queue-panel')).toContainText('queued followup'); await expect(page.getByRole('button', { name: 'Resume queue' })).toBeVisible();
  await page.getByRole('button', { name: 'Remove', exact: true }).click(); await expect(page.locator('.queue-panel')).toHaveCount(0);
});

test('imports image and text attachments, persists permissions, copies and edits messages, and collapses sidebar', async () => {
  const page = await launch(); const projectDir = join(dir, 'attachments-project'); execFileSync('/usr/bin/git', ['init', '-q', projectDir]);
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, projectDir);
  await page.locator('.welcome').getByRole('button', { name: 'Open project' }).click();
  const { writeFile } = await import('node:fs/promises');
  const imagePath = join(dir, 'example.png'), textPath = join(dir, '说明.md');
  await writeFile(imagePath, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=', 'base64')); await writeFile(textPath, 'Attached context');
  await app.evaluate(({ dialog }, paths) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: paths }); }, [imagePath, textPath]);
  await page.getByRole('button', { name: 'Add attachments', exact: true }).click(); await expect(page.locator('.composer-region .attachment-chip')).toHaveCount(2);
  await page.getByRole('combobox', { name: 'Permissions', exact: true }).click(); await page.getByRole('option', { name: 'Approve for me', exact: true }).click();
  await page.locator('#composer').fill('inspect-input'); await page.locator('#composer').press('Enter');
  await expect(page.locator('.markdown')).toContainText('localImage'); await expect(page.locator('.markdown')).toContainText('Attached context'); await expect(page.locator('.markdown')).toContainText('auto_review');
  await page.locator('.message-user').hover();
  await page.locator('[data-align=end] .message-actions').getByRole('button', { name: 'Copy message', exact: true }).click(); await expect.poll(() => app.evaluate(({ clipboard }) => clipboard.readText())).toBe('inspect-input');
  await page.getByRole('button', { name: 'Edit message', exact: true }).click(); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.locator('.user-text')).toHaveCount(1);
  await page.getByRole('button', { name: 'Edit message', exact: true }).click(); await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.locator('#composer')).toHaveValue('inspect-input'); await expect(page.locator('.composer-region .attachment-chip')).toHaveCount(2); await expect(page.locator('.session-row')).toHaveCount(2);
  await page.getByRole('button', { name: 'Toggle sidebar', exact: true }).click(); await expect(page.locator('.sidebar-frame')).toHaveAttribute('inert', '');
  await app.evaluate(({ Menu }) => { const item = Menu.getApplicationMenu()!.items.flatMap(i => i.submenu?.items || []).find(i => i.accelerator === 'CmdOrCtrl+B')!; item.click(); }); await expect(page.locator('.sidebar-frame')).not.toHaveAttribute('inert', '');
  await page.screenshot({ path: 'test-results/attachments-and-history.png' });
});

test('requires confirmation for project archive/delete and keeps code files', async () => {
  const page = await launch(store => { const project = store.addProject(dir); for (const title of ['One', 'Two']) { const s = store.createSession(project.id, 'codex'); store.updateSession(s.id, { title }); } });
  const { writeFile } = await import('node:fs/promises'); await writeFile(join(dir, 'keep.txt'), 'keep');
  await page.getByRole('button', { name: /Project actions/ }).click(); await page.getByRole('menuitem', { name: 'Archive project conversations' }).click(); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.locator('.session-row')).toHaveCount(2);
  await page.getByRole('button', { name: /Project actions/ }).click(); await page.getByRole('menuitem', { name: 'Archive project conversations' }).click(); await page.getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.locator('.session-row')).toHaveCount(0);
  await page.getByRole('button', { name: 'Archived sessions', exact: true }).click(); await expect(page.locator('.session-row')).toHaveCount(2);
  await page.getByRole('button', { name: /Project actions/ }).click(); await page.getByRole('menuitem', { name: 'Delete project', exact: true }).click(); await page.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(page.locator('.project-group')).toHaveCount(1);
  await page.getByRole('button', { name: /Project actions/ }).click(); await page.getByRole('menuitem', { name: 'Delete project', exact: true }).click(); await page.getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.locator('.project-group')).toHaveCount(0); expect(await readFile(join(dir, 'keep.txt'), 'utf8')).toBe('keep');
});

test('composer searches project context, selects skills and plan mode with keyboard, and exposes broad navigation targets', async () => {
 let projectId = '';
 const page = await launch(store => { projectId = store.addProject(dir).id; });
 const { mkdir, writeFile } = await import('node:fs/promises');
 await mkdir(join(dir, '中文 folder')); await writeFile(join(dir, '中文 folder', 'Application.tsx'), 'export const example = true;');
 await mkdir(join(dir, '.agents/skills/moose-fixture'), { recursive: true }); await writeFile(join(dir, '.agents/skills/moose-fixture/SKILL.md'), '---\nname: moose-fixture\ndescription: Test the current project\n---\nRead Application.tsx.');
 const input = page.locator('#composer');
 await input.fill('@aptsx'); await expect(page.getByRole('option', { name: /Application.tsx/ })).toBeVisible();
 await input.press('Enter'); await expect(input).toHaveValue('@"中文 folder/Application.tsx" ');
 await expect(page.locator('.context-chips')).toContainText('Application.tsx');
 await input.fill('/moose-fixture'); await expect(page.getByRole('option', { name: /moose-fixture/ })).toBeVisible(); await input.press('Tab');
 await input.fill('/plan'); await expect(page.getByRole('option', { name: /Plan mode/ })).toBeVisible();
 await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true }); await expect(input).toHaveValue('/plan');
 await input.press('Enter'); await expect(page.locator('.context-chips')).toContainText('Plan mode');
 await input.fill('inspect-input'); await input.press('Enter'); await expect(page.locator('.markdown')).toContainText('read-only');
 await expect(page.locator('.markdown')).toContainText('moose-fixture'); await expect(page.locator('.markdown')).toContainText('mention');
 const snapshot = await page.evaluate(() => window.moose.request('snapshot', {}));
 expect(snapshot.sessions[0].projectId).toBe(projectId);
 const messages = await page.evaluate(id => window.moose.request('messages', { sessionId: id }), snapshot.sessions[0].id);
 expect(messages.messages.find(m => m.kind === 'user')?.context?.mode).toBe('plan');
 await page.screenshot({ path: 'test-results/context-light.png' });
 await input.fill('/'); await expect(page.getByRole('option', { name: /Goal mode/ })).toBeVisible();
 await expect(page.getByRole('option', { name: /moose-fixture/ })).toBeVisible(); await page.screenshot({ path: 'test-results/slash-menu.png' }); await input.press('Escape');
 await page.getByRole('button', { name: 'Settings', exact: true }).click();
 const back = await page.getByRole('button', { name: 'Back', exact: true }).boundingBox();
 const general = await page.getByRole('button', { name: 'General', exact: true }).boundingBox();
 expect(back!.width).toBe(general!.width); expect(back!.height).toBeGreaterThanOrEqual(40);
});
